-- Using  Oracle Database 19c on https://livesql.oracle.com/

-- Inserting more people self-reporting symptoms:
INSERT INTO SYMPTOM VALUES(2, 29, TO_DATE('2023-09-13', 'YYYY-MM-DD'), 2, null);
INSERT INTO TEST VALUES(11, 'Company', TO_DATE('2023-09-13', 'YYYY-MM-DD'), 14, 29, 'negative', 2, null);
UPDATE SYMPTOM SET TEST_ID = 11 WHERE SYMPTOM_ROW_ID = 2;

INSERT INTO SYMPTOM VALUES(3, 10, TO_DATE('2023-09-13', 'YYYY-MM-DD'), 2, null);
INSERT INTO TEST VALUES(12, 'Company', TO_DATE('2023-09-13', 'YYYY-MM-DD'), 14, 10, 'negative', 3, null);
UPDATE SYMPTOM SET TEST_ID = 12 WHERE SYMPTOM_ROW_ID = 3;

INSERT INTO SYMPTOM VALUES(4, 10, TO_DATE('2023-09-13', 'YYYY-MM-DD'), 3, null);
INSERT INTO TEST VALUES(13, 'Company', TO_DATE('2023-09-13', 'YYYY-MM-DD'), 14, 10, 'negative', 4, null);
UPDATE SYMPTOM SET TEST_ID = 13 WHERE SYMPTOM_ROW_ID = 4;

INSERT INTO SYMPTOM VALUES(5, 10, TO_DATE('2023-09-13', 'YYYY-MM-DD'), 4, null);
INSERT INTO TEST VALUES(14, 'Company', TO_DATE('2023-09-13', 'YYYY-MM-DD'), 14, 10, 'negative', 5, null);
UPDATE SYMPTOM SET TEST_ID = 14 WHERE SYMPTOM_ROW_ID = 4;

SELECT SYMPTOM_ID, COUNT(*) as NO_OF_TIMES_SELF_REPORTED FROM SYMPTOM GROUP BY SYMPTOM_ID ORDER BY COUNT(*) DESC FETCH FIRST 1 ROWS ONLY;
